# Site settings
title: epokay.ai 
email: info@epokay.ai
description: > # this means to ignore newlines until "baseurl:"
  Epokay operates at the interface of the latest academic developments in machine learning and their deployment in industry, policy, health and the third sector.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://epokay.ai/" # the base hostname & protocol for your site

company:
  name: epokay.ai

more:
  link: "#contact"
  label: Find Out More
  
contact:
  title: Get In Touch!
  email: info@epokay.ai
  description: Ready to start your next project with us? Send us a message and we will get back to you as soon as possible!
  link: "#services"
  label: "Get Started!"
# Build settings
markdown: kramdown

about:
  title: "We've got what you need!"
  description: "Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!"
permalink: /:year/:month/:day/:title

masthead:
  image: /assets/img/bg-masthead.jpg

show:
  about: false
  call_to_action: false
  services: false
  portfolio: false
  contact: true

collections:
  news:
    output: true
  people:
    output: true
  resources:
    output: true
  projects:
    output: true

remote_theme: epokay/jekyll-theme
remote_theme: jekyll/minima

ghub:
  edit: true
  repository: epokay.github.io

# paginate: 4
# paginate_path: "blog/page:num"
# for paginate-v2 (not supported by github pages)
# pagination:
#   enabled: true
#   per_page: 4
#   permalink: "blog/page:num"
#   title_suffix: " - page :num"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# - jekyll-paginate
