# Site settings
title: epokay.ai 

description: > # this means to ignore newlines until "baseurl:"
  Epokay operates at the interface of the latest academic developments in machine learning and their deployment in industry, policy, health and the third sector.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://epokay.ai/" # the base hostname & protocol for your site

company:
  name: epokay.ai
  
contact:
  show: true
  title: Get In Touch!
  email: info@epokay.ai
  description: Ready to start your next project with us? Send us a message and we will get back to you as soon as possible!
  link: "#contact"
  label: "Contact"
# Build settings
markdown: kramdown

about:
  show: false
  title: "We've got what you need!"
  description: "Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!"
permalink: /:year/:month/:day/:title

masthead:
  link: "#contact"
  label: Find Out More  
  image: /assets/img/bg-masthead.jpg

call_to_action:
  show: false
  title: Free Download at Start Bootstrap!
  label: Download Now!
  link: https://startbootstrap.com/theme/creative/

services:
  title: At Your Service
  link: "#services"
  label: Services

projects:
  title: Portfolio
  link: "#portfolio"
  label: Portfolio
  
partners:
  title: Our Partners
  link: "#partners"
  label: Partners
  
collections:
  news:
    output: true
  people:
    output: true
  services:
    output: true
  projects:
    output: true
  partners:
    output: true
    
remote_theme: epokay/jekyll-theme
remote_theme: jekyll/minima

ghub:
  edit: true
  repository: epokay.github.io

# paginate: 4
# paginate_path: "blog/page:num"
# for paginate-v2 (not supported by github pages)
# pagination:
#   enabled: true
#   per_page: 4
#   permalink: "blog/page:num"
#   title_suffix: " - page :num"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# - jekyll-paginate
