# Site settings
title: epokay.ai 

description: > # this means to ignore newlines until "baseurl:"
  Epokay operates at the interface of the latest academic developments in machine learning and their deployment in industry, policy, health and the third sector.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://epokay.ai/" # the base hostname & protocol for your site

  
collections:
  news:
    output: true
  people:
    output: true
  services:
    output: true
  projects:
    output: true
  partners:
    output: true
    
remote_theme: epokay/jekyll-theme
remote_theme: jekyll/minima

ghub:
  edit: true
  repository: epokay.github.io

# paginate: 4
# paginate_path: "blog/page:num"
# for paginate-v2 (not supported by github pages)
# pagination:
#   enabled: true
#   per_page: 4
#   permalink: "blog/page:num"
#   title_suffix: " - page :num"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# - jekyll-paginate
