backend:
  name: github # git-gateway
  repo: epokay/epokay.github.io
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/images'

collections:
  # General Website Settings
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      # Website Settings
      - label: 'Website Settings'
        name: 'site'
        file: '_data/site.yml'
        editor:
          preview: false
        fields:
          - lable: 'Title'
            name: title
            widget: 'string'
          # Call to Action Details
          - label: 'Call to Action'
            name: call_to_action
            collapsed: true
            widget: 'object'
            fields:
              - label: "Enable"
                name: 'show'
                widget: 'boolean'
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Link label'
                name: 'label'
                widget: 'string'
          # Services Details 
          - label: 'Services'
            name: services
            collapsed: true
            widget: 'object'
            fields:
              - label: "Enable"
                name: 'show'
                widget: boolean
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'

          # Partner Details 
          - label: 'Partners'
            name: partners
            collapsed: true
            widget: 'object'
            fields:
              - label: "Enable"
                name: 'show'
                widget: boolean
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Link label'
                name: 'label'
                widget: 'string'                
          # Contact Details
          - label: 'Contact Info'
            name: 'contact'
            collapsed: true
            widget: 'object'
            fields:
              - label: "Enable"
                name: 'show'
                widget: boolean
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'markdown'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Link label'
                name: 'label'
                widget: 'string'
              - label: 'Address'
                name: 'address'
                widget: 'markdown'
                required: false
              - label: 'Tel'
                name: 'tel'
                widget: 'string'
                required: false
              - label: 'Fax'
                name: 'fax'
                widget: 'string'
                required: false
              - label: 'Email'
                name: 'email'
                widget: 'string'
          # About Details
          - label: 'About the company'
            name: 'about'
            collapsed: true
            widget: 'object'
            fields:
              - label: "Enable"
                name: 'show'
                widget: boolean
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'markdown'
          # Masthead images
          - label: 'Masthead Image'
            name: 'masthead'
            collapsed: true
            widget: 'object'
            required: true
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Link label'
                name: 'label'
                widget: 'string'
          # Social Details
          - label: 'Social Details'
            name: 'social_details'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Twitter'
                name: 'twitter_link'
                widget: 'string'
                required: false
              - label: 'Facebook'
                name: 'facebook_link'
                widget: 'string'
                required: false
              - label: 'Instagram'
                name: 'instagram_link'
                widget: 'string'
                required: false
          # Collections Settings
          - label: 'News'
            name: 'news'
            widget: 'object'
            fields:
              - label: 'Show'
                name: 'show'
                widget: 'boolean'
                required: false
          - label: 'People'
            name: 'people'
            widget: 'object'
            fields:
              - label: 'Show'
                name: 'show'
                widget: 'boolean'
                required: false
          - label: 'Projects'
            name: 'projects'
            widget: 'object'
            fields:
              - label: 'Show'
                name: 'show'
                widget: 'boolean'
                required: false
              - label: "Title"
                name: 'title'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Link label'
                name: 'label'
                widget: 'string'


  # News Collection
  - label: 'News'
    name: 'News'
    folder: '_news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'news-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'research'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        options_length: 999
        multiple: true
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # Services Collection
  - label: 'Services'
    name: 'services'
    folder: '_services'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Bootstrap Icon'
        name: 'icon'
        widget: 'string'
        hint: "These are bootstrap icons. See the full list here https://icons.getbootstrap.com (prefix with bi- ... i.e. heart is bi-heart)."
      - label: 'Description'
        name: 'description'
        widget: 'markdown'
  
  # People Collection
  - label: 'People'
    name: 'people'
    folder: '_people/'
    create: true
    slug: '{{given}}-{{family}}'
    identifier_field: crsid
    editor:
      preview: false
    fields:
    - label: 'Layout'
      name: 'layout'
      widget: 'hidden'
      default: 'person'
    - label: Given Name
      hint: "Include initials, e.g. Neil D."
      name: given
      widget: string
    - label: Preferred Name
      hint: "If you don't normally use your full given name (e.g. you are known as Nick not Nicholas)"
      name: preferred
      required: false
      widget: string
    - label: Family Name
      name: family
      widget: string
    - label: Prefix
      hint: Prefix of name (e.g. de, von, van)
      name: prefix
      required: false
      widget: string
    - label: Suffix
      hint: "Suffix of name (e.g. III or Jr)."
      name: suffix
      required: false
      widget: string
    - label: "Cambridge crsid"
      hint: "E.g. ads21. If a ml@cl member doesn't have a crsid create a dummy one starting with five x's, e.g. xxxxx01."
      name: 'crsid'
      widget: 'string'
    - label: Student
      name: student
      widget: "boolean"
      required: false
    - name: start
      label: "Date of start in ml@cl"
      hint: "Provide the day that the individual started in the ml@cl group."
      widget: 'datetime'
      format: "YYYY-MM-DD"
      date_format: "YYYY-MM-DD"
      time_format: false
    - name: end
      label: "Date of finish in ml@cl"
      hint: "Provide the day that the individual finished in the ml@cl group."
      widget: 'datetime'
      format: "YYYY-MM-DD"
      date_format: "YYYY-MM-DD"
      time_format: false
      default: ""
      required: false
    - label: "Personal Homepage"
      name: website
      hint: "URL of the individual's personal homepage."
      widget: "string"
      required: false
    - label: "ORCID number"
      name: orcid
      hint: "Open Researcher and Contributor ID number (see https://orcid.org)"
      widget: "string"
      required: false
    - label: 'Position'
      name: 'position'
      widget: 'string'
      hint: "For example, PhD Student, MPhil Student, Lecturer etc."
    - label: 'Institution'
      name: 'institution'
      hint: "For example, Cambridge University."
      widget: 'string'
    - label: 'Image'
      hint: "Please provide a portrait of the person."
      name: 'image'
      widget: 'image'
      required: false
    - label: 'GitHub ID'
      name: 'github'
      widget: 'string'
      required: false
    - label: 'LinkedIn ID'
      name: 'linkedin'
      widget: 'string'
      required: false
    - label: 'Twitter'
      name: 'twitter'
      widget: 'string'
      required: false
    - label: 'Facebook'
      name: 'facebook'
      widget: 'string'
      required: false
    - label: 'Email'
      name: 'email'
      widget: 'string'
      required: false
    - label: 'Biography'
      name: 'biography'
      widget: 'markdown'
      required: false
    - label: 'Projects'
      name: 'projects'
      widget: 'relation'
      collection: 'Projects'
      search_fields: ["title"]
      value_field: "{{slug}}"
      display_fields: ["title"]
      options_length: 999
      multiple: true
      required: false
    - label: 'Body'
      name: 'body'
      widget: 'markdown'
      required: false


  # Partner Collection
  - label: 'Partners'
    name: 'partners'
    folder: '_partners/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'partner-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # Project Collection
  - label: 'Projects'
    name: 'projects'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'project-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Project Funders'
        name: 'project_funders'
        collapsed: true
        minimize_collapsed: true
        required: false
        widget: 'list'
        fields: 
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Link'
            name: 'link'
            widget: 'string'
      - label: 'Related People'
        name: 'people'
        widget: 'relation'
        collection: 'people'
        search_fields: ["given", "family"]
        value_field: "{{slug}}"
        display_fields: ["given", "family"]
        options_length: 999
        multiple: true
        required: false

  # Opportunities Collection
  - label: 'Opportunities'
    name: 'opportunities'
    folder: '_opportunities/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'opportunities-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'    
